from datetime import datetime
from typing import Dict, List
from reviewagent.review import FileReviewResult, Finding


def compute_file_severity_rank(findings: List[Finding]) -> int:
    """
    Lower score = more severe.
    Bugs take highest precedence, then logic, then style.
    """
    if not findings:
        return 999
    
    severities = {f.severity for f in findings}
    if "bug" in severities:
        return 1
    if "logic" in severities:
        return 2
    if "style" in severities:
        return 3
    return 4


def generate_markdown_report(
    repo_url: str,
    results: List[FileReviewResult],
    model_name: str,
) -> str:
    total_files = len(results)
    all_findings = [f for r in results for f in r.findings]
    
    bug_count = sum(1 for f in all_findings if f.severity == "bug")
    logic_count = sum(1 for f in all_findings if f.severity == "logic")
    style_count = sum(1 for f in all_findings if f.severity == "style")
    total_issues = len(all_findings)

    # Sort files by worst severity first, then by finding count descending
    sorted_results = sorted(
        results,
        key=lambda r: (compute_file_severity_rank(r.findings), -len(r.findings), r.file_path),
    )

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# Code Review Report",
        f"",
        f"- **Repository:** `{repo_url}`",
        f"- **Date:** {now}",
        f"- **Review Model:** `{model_name}`",
        f"- **Files Analyzed:** {total_files}",
        f"- **Total Findings:** {total_issues} ({bug_count} bugs, {logic_count} logic errors, {style_count} style issues)",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"| Metric | Count |",
        f"|---|---|",
        f"| Total Files Checked | {total_files} |",
        f"| Critical Bugs | {bug_count} |",
        f"| Logic Errors | {logic_count} |",
        f"| Style & Maintainability | {style_count} |",
        f"",
    ]

    if total_issues == 0:
        lines.append("No defects, logic errors, or style violations were detected in the reviewed files.")
        return "\n".join(lines)

    lines.append("## Detailed File Findings")
    lines.append("")

    for res in sorted_results:
        file_findings = res.findings
        file_bug_count = sum(1 for f in file_findings if f.severity == "bug")
        file_logic_count = sum(1 for f in file_findings if f.severity == "logic")
        file_style_count = sum(1 for f in file_findings if f.severity == "style")

        status_tag = "CLEAN"
        if file_bug_count > 0:
            status_tag = f"CRITICAL ({file_bug_count} bugs)"
        elif file_logic_count > 0:
            status_tag = f"WARNING ({file_logic_count} logic)"
        elif file_style_count > 0:
            status_tag = f"NOTICE ({file_style_count} style)"

        lines.append(f"### `{res.file_path}` — [{status_tag}]")
        lines.append("")
        
        if res.summary:
            lines.append(f"*{res.summary}*")
            lines.append("")

        if not file_findings:
            lines.append("No issues found in this file.")
            lines.append("")
            continue

        # Sort findings within the file by line number
        ordered_findings = sorted(file_findings, key=lambda f: f.line)

        for f in ordered_findings:
            severity_label = f.severity.upper()
            lines.append(f"#### Line {f.line} — [{severity_label}] {f.title}")
            lines.append(f"**Description:** {f.description}")
            if f.suggestion:
                lines.append(f"")
                lines.append(f"**Suggested Fix:**")
                lines.append(f"```python")
                lines.append(f"{f.suggestion.strip()}")
                lines.append(f"```")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by code-review-agent. Use `reviewagent followup <file> \"<question>\"` to ask follow-up questions about any file.*")

    return "\n".join(lines)
